### ISSUE TITLE
Can't create jar

### ISSUE THREAD

**Issue by mayanks43** [ibtawfik/nanomunchers#1]
Ran "mvn clean package" on first level of repository. Didn't run this on /src bcoz it says missing pom.xml.

Error:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Unnamed - NanoMunchers:NanoMunchers:jar:1.0
[INFO]    task-segment: [clean, package]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] Deleting /home/marcus/nanomunchers/target
[INFO] [resources:resources {execution: default-resources}]
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 6 resources
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Unable to get dependency information: Unable to read the metadata file for artifact 'org.glassfish.hk2:hk2-api:jar': Invalid JDK version in profile 'javadoc-jdk8+': Unbounded range: [1.8 for project unknown:hk2-parent
  org.glassfish.hk2:hk2-api:jar:2.4.0-b31

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  sonatype-nexus-snapshots (http://oss.sonatype.org/content/repositories/snapshots)

Path to dependency: 
    1) NanoMunchers:NanoMunchers:jar:1.0
    2) io.dropwizard:dropwizard-core:jar:0.9.0
    3) io.dropwizard:dropwizard-jersey:jar:0.9.0
    4) org.glassfish.jersey.core:jersey-server:jar:2.22.1
    5) org.glassfish.jersey.core:jersey-common:jar:2.22.1

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Tue Nov 10 23:27:04 EST 2015
[INFO] Final Memory: 18M/173M
[INFO] ------------------------------------------------------------------------

**Comment by ibtawfik** [comment]
I'n not able to recreate the problem with either java 8 or java 7. It might
be that that the version number on line 31 of the pom is related to the
java version you are running. Try it with <version>1.8</version> instead of
<version>1.7</version*> \* but honestly I don't think that is the problem.

Here is what the error says on the internet.
https://java.net/jira/browse/HK2-277. Maybe try upgrading to maven 3.3.3
and see if you still get the error.

**Comment by mayanks43** [comment]
Yeah upgrading to 3.3.3 helps.
