### ISSUE TITLE
Too much spam on server

### ISSUE THREAD

**Issue by mayanks43** [ibtawfik/nanomunchers#2]
I keep getting these messages when I have the ui loaded in the browser. Can you disable them or suggest how to do it? They hide useful information from the server. 

127.0.0.1 - - [<time>] "GET /game-state HTTP/1.1" 200 - "http://localhost:8080/assets" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36" 2

Btw great job with the UI! :clap: 
One suggestion is make the player colors more contrasting. Yellow and orange are pretty close.

**Comment by ibtawfik** [comment]
Changed the log level to off from info

**Comment by dkelmer** [comment]
Is there some additional flag we need to set or something we need to do ourselves to get rid of the logs? I pulled the changes and tried rebuilding the project and deleting and rebuilding the project but the log messages are still getting printed

**Comment by ibtawfik** [comment]
Hm ...I thought that was resolved.  I'll take another look and get back to you.

**Comment by ibtawfik** [comment]
So I haven't been able to figure it out. The server is printing the request logs. This should be configurable but the configs don't seem to take. Why do you need to look at the servers logs anyway?  Shouldn't you just be looking at your clients logs?

**Comment by dkelmer** [comment]
Thanks for looking into it again. I was printing some stuff out but I can do without. I was just wondering if you had already fixed it how to get it to work.
