### ISSUE TITLE
Error in score calculation

### ISSUE THREAD

**Issue by KshitizSethia** [ibtawfik/nanomunchers#5]
Hi,

Here's the score on the UI:
![image](https://cloud.githubusercontent.com/assets/4375768/11171385/f4b9005e-8bbc-11e5-8930-70cf6f83ec9a.png)

It's clear that P1 has score 3, but the score is being shown as 5. I suspect the error is at Game.java, line 225

**Comment by ibtawfik** [comment]
Yeah there is some kind of lag in the update. Looking into this, but it seems that the game final score is correct, I'll fix your other issue first then get back to this one.

**Comment by ibtawfik** [comment]
Fixed. Becuase of a time lag between the player class and the node class you were seeing scores early. Have scores coming from the node class, appears to work now.
